### ISSUE TITLE
src-cli-5.1.1 fails to build

### ISSUE THREAD

**Issue by williamh** [sourcegraph/src-cli#1018]
Hi all, I am the sourcegraph-cli package maintainer on Gentoo linux.
I am attempting to build sourcegraph-cli-5.1.1 with go 1.21 and getting the following:
```
william@linux1 src-cli $ pwd
/home/william/repos/github.com/sourcegraph/src-cli
william@linux1 src-cli $ git zap
william@linux1 src-cli $ git describe --tags
5.1.1
william@linux1 src-cli $ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
william@linux1 src-cli $ go build ./cmd/src
# golang.design/x/clipboard
clipboard_linux.c:15:10: fatal error: X11/Xlib.h: No such file or directory
   15 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
william@linux1 src-cli $
```

It looks like you have a dependency missing in ```developing.md```.

Can you let me know what I'm missing?

Thanks,

William

**Comment by williamh** [comment]
Hey @mrnugget thanks for the info.
Based on this, it looks like src-cli now has a hard dependency on libX11.
Can this be made optional some how so src-cli can still be used on non-X11 systems?

Thanks,

William

**Comment by mrnugget** [comment]
cc @jasonhawkharris who worked on the `scout` functionality which uses this. Jason, do you think you really need the `clipboard` functionality? Or is there maybe a different lib we could use without these build-time dependencies?

**Comment by jasonhawkharris** [comment]
PR #1022
