### ISSUE TITLE
wrong powershell instructions for setting env variables 

### ISSUE THREAD

**Issue by DanielJump** [sourcegraph/src-cli#1024]
On this page:
https://github.com/sourcegraph/src-cli#installation

It says:
$env.SRC_ENDPOINT = 'https://sourcegraph.example.com'
$env.SRC_ACCESS_TOKEN = 'my-token'

It should be:
$env:SRC_ENDPOINT = 'https://sourcegraph.example.com'
$env:SRC_ACCESS_TOKEN = 'my-token'

**Comment by mrnugget** [comment]
Thanks for reporting. Fix is here: https://github.com/sourcegraph/src-cli/pull/1025
