### ISSUE TITLE
Binary download broken on 3.12.5

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/src-cli#103]
1. Ensure 3.12.5 is the current version.
1.  Request binary from the instance (https://a8n-demo.sgdev.org/.api/src-cli/src_linux_amd64)
1. Observe that the redirect URL is interpreted by Sourcegraph as a repo search (https://a8n-demo.sgdev.org/github.com/sourcegraph/src-cli/releases/download/3.10.3/src_linux_amd64)

**Comment by efritz** [comment]
This was fixed in https://github.com/sourcegraph/sourcegraph/pull/8139.

Does this fix need to be backported to the 3.12 branch?

**Comment by ryan-blunden** [comment]
The docs indicate you can use the instance url on 3.12 or later so while I would say yes, if this is not something anyone else has complained about, then you can just update the docs to use this if running 3.13 or later.
