### ISSUE TITLE
Unzip failed with interactive message

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/src-cli#109]
**unzip version**: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.`
**OS**: `macOS Catalina 10.15.3`
Error log:

```
Unzipping the ZIP archive failed: unzip failed: exit status 1: replace /tmp/action-sd9-akita694954415/angular/playground/projects/ng-entity-service/src/lib/ng-entity-service-notifier.ts? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```

```
# Repository github.com/sd9/akita @ refs/heads/master (1 steps)
# ERROR: Unzipping the ZIP archive failed: unzip failed: exit status 1: replace /tmp/action-sd9-akita391331449/angular/playground/projects/ng-entity-service/src/lib/ng-entity-service-notifier.ts? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```

action file: 
```
{
  "scopeQuery": "repo:github.com/sd9/* repohasfile:^package.json",
  "steps": [
    {
      "type": "command",
      "args": ["sed", "-i", "", "s/\"main\"/\"es2015\"/", "package.json"]
    }
  ]
}
```

**Comment by eseliger** [comment]
I just saw some other errors popping up:
- [ ] webchat_web_devtools
```
# Repository github.com/sd9/wechat_web_devtools @ refs/heads/master (1 steps)
# ERROR: Unzipping the ZIP archive failed: unzip failed: exit status 50: checkdir error:  cannot create /tmp/action-sd9-wechat_web_devtools742807097/Tencent/ե��+��+�������������
                 Illegal byte sequence
                 unable to process Tencent/ե��+��+�������������/.
error:  cannot create /tmp/action-sd9-wechat_web_devtools742807097/images/ե��+����������.jpeg
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-wechat_web_devtools742807097/images/�����1.png
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-wechat_web_devtools742807097/images/ަ�޻�������.png
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-wechat_web_devtools742807097/package.nw/node_modules/git-utils/deps/libgit2/tests/resources/status/�+�
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-wechat_web_devtools742807097/package.nw/node_modules/nodegit/vendor/libgit2/tests/resources/status/�+�
        Illegal byte sequence
``` (I assume there are chinese characters or something in the filenames

- [ ] meedu
```
# Repository github.com/sd9/meedu @ refs/heads/master (1 steps)
# ERROR: Unzipping the ZIP archive failed: unzip failed: exit status 50: error:  cannot create /tmp/action-sd9-meedu946649789/docs/api/v1/�+����������.md
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-meedu946649789/docs/api/v1/�+����.md
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-meedu946649789/docs/api/v1/�����������.md
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-meedu946649789/docs/api/v1/��+բ������.md
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-meedu946649789/docs/api/v1/޺���������.md
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-meedu946649789/docs/api/v1/޻���������.md
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-meedu946649789/docs/ի���������.md
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-meedu946649789/docs/իܵ������+�.md
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-meedu946649789/docs/���ަ�޺����.md
        Illegal byte sequence
error:  cannot create /tmp/action-sd9-meedu946649789/docs/���޻�������.md
        Illegal byte sequence
```

- [ ] react-quill, sourcegraph, sourcegraph-1
```
# Repository github.com/sd9/react-quill @ refs/heads/master (1 steps)
# Step 0: command [sed -i  s/"main"/"es2015"/ package.json]
# Step 0: done.
# ERROR: Generating a diff failed: diff (output was: "diff: /tmp/action-sd9-react-quill217582422/demo/prop-types.js: No such file or directory\ndiff: /tmp/action-sd9-react-quill257717011/demo/prop-types.js: No such file or directory\ndiff: /tmp/action-sd9-react-quill217582422/demo/quill.snow.css: No such ..."): exit status 2
```
```
# Repository github.com/sd9/sourcegraph @ refs/heads/master (1 steps)
# Step 0: command [sed -i  s/"main"/"es2015"/ package.json]
# Step 0: done.
# ERROR: Generating a diff failed: diff (output was: "diff: /tmp/action-sd9-sourcegraph155004138/browser/node_modules/.bin: No such file or directory\ndiff: /tmp/action-sd9-sourcegraph206286072/browser/node_modules/.bin: No such file or directory\ndiff: /tmp/action-sd9-sourcegraph155004138/client/browser/..."): exit status 2
```
```
# Repository github.com/sd9/sourcegraph-1 @ refs/heads/master (1 steps)
# Step 0: command [sed -i  s/"main"/"es2015"/ package.json]
# Step 0: done.
# ERROR: Generating a diff failed: diff (output was: "diff: /tmp/action-sd9-sourcegraph-1001303361/browser/node_modules/.bin: No such file or directory\ndiff: /tmp/action-sd9-sourcegraph-1256487927/browser/node_modules/.bin: No such file or directory\ndiff: /tmp/action-sd9-sourcegraph-1001303361/client/br..."): exit status 2
```

**Comment by eseliger** [comment]
Update: this is only on macOS, running in linux doesn't yield this problem. Apparently, it's due to APFS:
https://github.com/CocoaPods/CocoaPods/issues/7711

**Comment by eseliger** [comment]
Update: the `react-quill`, `sourcegraph-1` and `sourcegraph` repos failed because macOS doesn't support the `--no-dereference` flag. **todo** should we make the lack of this flag more prominent when such an error occurs? 🤔

**Comment by slimsag** [comment]
Go has a really nice zip package, why aren't we using that instead of shelling out to `zip`? https://sourcegraph.com/github.com/sourcegraph/src-cli/-/blob/cmd/src/actions_exec_backend_runner.go#L311

**Comment by mrnugget** [comment]
> Update: the `react-quill`, `sourcegraph-1` and `sourcegraph` repos failed because macOS doesn't support the `--no-dereference` flag. **todo** should we make the lack of this flag more prominent when such an error occurs? 🤔

Yeah, the version on macOS is incredibly outdated. We can print a warning in the logs if we detect that the version doesn't support the flags we need.


> Go has a really nice zip package, why aren't we using that instead of shelling out to `unzip`?

No hard reason. If I had to guess I'd say it was easier to use?

**Comment by mrnugget** [comment]
> Update: the issue with wechat and meedu is only on macOS, running in linux doesn't yield this problem. Apparently, it's due to APFS:
> [CocoaPods/CocoaPods#7711](https://github.com/CocoaPods/CocoaPods/issues/7711)

Yeah, there's another issue with APFS: it's case-insensitive by default, whereas most Linux filesystems are case-sensitive by default. And, guess what, some repos have a `readme.md` and a `README.md`. That breaks on macOS.

**Comment by mrnugget** [comment]
@eseliger Which of the issues you reported here were fixed by installing a newer version of `diff`, which ones are due to APFS and which ones are independent and can be fixed by us?

**Comment by eseliger** [comment]
the issues related to react-quill, sourcegraph, sourcegraph-1 are fixed by updating `diff` as they had softlinks to files that aren't present in the repo

**Comment by eseliger** [comment]
Leftover are the issue originially posted with the interactive prompt from `unzip` and the issue with the chinese characters (which is a little weird because macOS's internal unzipper tool from finder _can_ unzip it correctly and the folder has the correct name)

**Comment by mrnugget** [comment]
So the issues left are:

1. Unzipping ZIP archives that include files with the same case-independent name fails on macOS because APFS is case-insensitive:
<img width="1049" alt="Screen Shot 2020-02-20 at 14 34 06" src="https://user-images.githubusercontent.com/1185253/74938391-35505380-53ee-11ea-8887-fc15e55a15d3.png">
2. Unzipping files with chinese characters in the name. Interestingly enough, GitHub's own "Download ZIP" functionality gives me a ZIP file that does **not** include those files:

<img width="349" alt="Screen Shot 2020-02-20 at 14 45 08" src="https://user-images.githubusercontent.com/1185253/74939106-9af10f80-53ef-11ea-8f48-964858a6bc99.png">

vs.

<img width="1134" alt="Screen Shot 2020-02-20 at 14 45 23" src="https://user-images.githubusercontent.com/1185253/74939127-a3e1e100-53ef-11ea-8186-1a32d8472267.png">

**Comment by eseliger** [comment]
Ah yep the first makes sense, my bad I didn't see that on first sight.

The latter, that is weird behavior from GitHubs side I think 😀 Given that it's not impossible with APFS, as the internal finder tool can correctly unzip it, maybe we should give the go zip library a try and even get around that dependency on `unzip`? 🤔 (not sure that can handle it better though, but might be worth a spike)

**Comment by mrnugget** [comment]
>  maybe we should give the go zip library a try and even get around that dependency on `unzip`? 🤔 (not sure that can handle it better though, but might be worth a spike)

Yep, I've got it working locally. Will push a commit/PR later today.
