### ISSUE TITLE
a8n: Doesn't support namespaced Docker image names e.g, sourcegraph/rxjs-upgrade

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/src-cli#113]
If using a Docker image name such as `sourcegraph/rxjs-upgrade` is used as the , the CLI will output an empty array `[]`.

**Comment by mrnugget** [comment]
Hmm, are you sure? Can I see your action definition? Because I suspect that you did not specify the `"image"` field, which will silently fail (fix is on the way)

**Comment by mrnugget** [comment]
Validation fix is here: https://github.com/sourcegraph/src-cli/pull/120

**Comment by mrnugget** [comment]
@ryan-blunden can you confirm that this issue still persists, even after #120?

**Comment by ryan-blunden** [comment]
Cannot re-produce now, thanks!
