### ISSUE TITLE
search and scopeQuery return different number of results

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/src-cli#125]
Wanted to construct a scope query that returned the `sourcegraph` and `basic-code-intel` repos.

The following search returns 2 results using `src search` but only one result when using `scopeQuery`:

```
repo:github\.com\/sourcegraph\/sourcegraph$|basic-code-intel$ repohasfile:yarn.lock file:^package.json$ rxjs patterntype:regexp
```

**Comment by ryan-blunden** [comment]
The issue appears to be with the escaping of the period and forward slashes in the repo string

**Comment by mrnugget** [comment]
You're correct: the backslash is an escape character in JSON, which means that it will be interpreted as such when reading the JSON file. In practical terms: JSON thinks you want to esacape the forward-slash (even though that's not necessary) and doesn't pass the backslash on. `\/` in the search string is passed on as `/` (which is NOT what you want).

(Also note that the `\.` is not valid JSON. Try running your action definition through `jq` and you'll get an error: `jq < my_action.json`)

I hope this here helps to remedy the problem: https://github.com/sourcegraph/src-cli/pull/135

**Comment by ryan-blunden** [comment]
Thanks for the clarification and the verbose logging will be very helpful.
