### ISSUE TITLE
Don't fail actions exec if only a subset of repositories failed

### ISSUE THREAD

**Issue by sd9** [sourcegraph/src-cli#129]
This is from @christinaforney who was in a demo browser tab when creating this issue.

When I had failures in any repository, there was not a valid `patches.json` created for me (an empty file was created, but there were no diffs/content, so I couldn't push it to Sourcegraph to create the preview). This means that I'm completely blocked on starting a campaign until I resolve (or exclude) any failing repository. 

Instead, I would like to be able to push up a valid `patches.json` from all of the repositories where my actions did not fail to preview and get started with kicking off my campaign. I can then come back to the failures to add them in later, so I should have a separate list (even just printed at the end) that tells me all the failed repos that I need to resolve. Some of the data we show already is good and helpful here, but we could summarize in a nicer way at finish, e.g. 3/10 repositories failed: <list repositories + links to error logs>. I can then push an update to my campaign once I've resolved each of these repositories (either caching the changes to repos that previously succeeded or by creating a way for me to add an individual diff for a repository to an existing campaign.

**Comment by mrnugget** [comment]
@christinaforney I've updatd the title to better reflect the content of this issue. Can you check whether it's valid?

And I agree that this is an issue. I also know how to solve it... kinda. The main blocker for me is the "UI" that will become really unwieldy, since we print our logs/messages on stderr and the patches on stdout. But I'll see what's possible.

**Comment by christinaforney** [comment]
> Can you check whether it's valid?

Yes, that's correct.

**Comment by christinaforney** [comment]
> Can you check whether it's valid?

Yes, that's correct.

**Comment by mrnugget** [comment]
I think this issue was largely fixed with https://github.com/sourcegraph/src-cli/pull/142 there's still some nice things we can do about the retrying that I want to tackle separately
