### ISSUE TITLE
Support filling in an extension's publisher

### ISSUE THREAD

**Issue by sqs** [sourcegraph/src-cli#13]
It would be nice if `src extensions publish` could fill in the publisher with the access token's username. This would make it easier for users who want to publish a "fork" or local dev copy of an extension. It would mean they would not need to temporarily edit package.json to add a `"publisher": "jsmith"` property (and remember to avoid committing their changes).

**Comment by felixfbecker** [comment]
I would be afraid to accidently republish extensions from a personal account that are published by an org

**Comment by eseliger** [comment]
Extensions have been deprected, so I am going to close this ticket as part of some backlog grooming. Please reopen if you think we should still care about it.
