### ISSUE TITLE
a8n: Node package upgrade campaign not failing when yarn-error.log file produced

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/src-cli#131]
When running a campaign to upgrade RxJS, 4 repositories had `yarn-error.log` files added as part of their diff. You can see the results of this draft campaign at https://demo.sgdev.org/campaigns/Q2FtcGFpZ246NQ== (admin user login details in password app).

The issue is that I expected to see a failure in the campaign exec results seeing as though a `yarn-error.log` file was produced.

What is also weird is that if I run a campaign targetting only one of these repositories such as `lsp-client`, the `yarn-error.log` file is not created and therefore not added to the diff.

## To reproduce

> NOTE: Requires access to a Sourcegraph instance that has synced affiliated repositories for the sd9 GitHub user.

Run an RxJS upgrade campaign for repos owned by the GitHub sd9 user using the commands:

```shell
git clone https://github.com/sourcegraph/campaign-examples.git
cd campaign-examples/rxjs-upgrade
make exec ACTION=sd9.action.json
make campaign-plan
```

Create a draft campaign and you should see multiple instances of `yarn-error.log` as part of the campaign diff.

**Comment by eseliger** [comment]
On first try I didn't get that behavior, so have to dig deeper tomorrow.
But I could imagine it's because the `rxjs-upgrade.sh` is missing a 
```bash
set -eo pipefail
```

**Comment by ryan-blunden** [comment]
Ok, will add that and try-again.

**Comment by eseliger** [comment]
did that help?

**Comment by ryan-blunden** [comment]
Yes, that did the trick, thanks!
