### ISSUE TITLE
Diff produced by src actions exec doesn't respect gitignore

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/src-cli#137]
It seems that auto-generated files that are ignored by `.gitignore` such as [schema files](https://github.com/sourcegraph/sourcegraph/blob/master/.gitignore#L104) still make there way into a campaign plan.

To reproduce:

```
git clone https://github.com/sourcegraph/campaign-examples.git
cd campaign-examples/rxjs-upgrade
make exec # You may want to change the scopeQuery to just be sourcegraph
make campaign-plan
```

Follow the link to view the campaign plan in the UI and observe schema files in the diff [( see this example campaign on sgdemo)](https://demo.sgdev.org/campaigns/Q2FtcGFpZ246Ng==).

**Comment by mrnugget** [comment]
To clarify: the bug is "diff doesn't respect .gitignore", right?

**Comment by eseliger** [comment]
I think so. At least that is _one_ bug or at least a source for confusion

**Comment by mrnugget** [comment]
While `diff` (from `GNU diffutils` at least) accepts an `--exclude-from=<file-with-ignore-patterns>` flag, there's two problems preventing us from simply using `--exclude-from=fresh-folder/.gitignore`:

1. The patterns in `.gitignore` are often relative to the folder in which they're specified (Example: `./foobar` in `/.gitignore` only ignores `/foobar` but not `/vendor/foobar`). When we're running `diff`, we're on level up and the patterns don't match anymore. AFAICT there's no way to tell `diff` to respect `.gitignore` files natively
2. `git` allows `.gitignore` in every subfolder, which doesn't seem transferrable to `--exclude-from`
