### ISSUE TITLE
src extensions publish does not work correctly on Windows

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/src-cli#19]
https://github.com/sourcegraph/src-cli/blob/4e548d9ca9a9a4316bf4692773f44bd19f5386dc/cmd/src/extensions_publish.go#L174

The expected behaviour here would be what npm does, which is using `cmd` on Windows. This decision is automatically made by Node `child_process.exec()`.

https://github.com/sourcegraph/src-cli/blob/4e548d9ca9a9a4316bf4692773f44bd19f5386dc/cmd/src/extensions_publish.go#L175

Windows uses `;` to separate `PATH`, not `:`.

**Comment by eseliger** [comment]
Extensions have been deprected, so I am going to close this ticket as part of some backlog grooming. Please reopen if you think we should still care about it.
