### ISSUE TITLE
Include instructions after src action exec

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/src-cli#202]
Add some instructions to src action exec when everything went well and we print a patch to stdout. 

Print instructions to STDERR after the json has been dumped.

**Comment by mrnugget** [comment]
A thought I had: maybe we should rethink dumping the patch to stdout and instead use a default location, like `./patches.json`, that can be overwritten with `-o`. The message is then something like "Patches saved to `patches.json`. Use 'src action patchset create-from-patches -f patches.json` ..."

**Comment by ryanslade** [comment]
If we make creating a file the default do we still want to handle the case where they pipe the output to create patches? eg:

```
src actions exec -f ~/run-gofmt.json | src campaign patchset create-from-patches
```

We could check if stdout is pointing at a pipe 'tee' output there too in that case?

**Comment by mrnugget** [comment]
> We could check if stdout is pointing at a pipe 'tee' output there too in that case?

I think that's a good default, yes.

- If `-o filename` is given, write to `filename`.
- If no `-o filename` is given and stdout is not a pipe, write to `patches.json`.
- If no `-o filename` is given and stdout _is_ a pipe, write to pipe.

**Comment by ryanslade** [comment]
Yep, working on the instructions now
