### ISSUE TITLE
include macports installation instructions for CLI

### ISSUE THREAD

**Issue by grimreaper** [sourcegraph/src-cli#212]
I prefer using a package manager over `curl | bash` for installation for obvious reasons. Macports is also preferred over homebrew for system security, stability, and ease-of-use reasons.

Would it be possible to support macports as a package manager for the CLI?

**Comment by manfredwedderin** [comment]
> I prefer using a package manager over `curl | bash` for installation for obvious reasons. Macports is also preferred over homebrew for system security, stability, and ease-of-use reasons.
> 
> Would it be possible to support macports as a package manager for the CLI?

**Comment by mrnugget** [comment]
Hey!

> I prefer using a package manager over `curl | bash` for installation for obvious reasons.

We don't recommend any installation method that includes `curl | bash`, though. The easiest installation method requires `curl` (or `wget`, or ...) simply to download a binary. What you then do with that binary is up to you.

> Would it be possible to support macports as a package manager for the CLI?

We currently use [goreleaser](https://goreleaser.com/) to cut releases and that doesn't have built-in macports support. So right now I think supporting macports is out of our scope. 

From what I can tell, though, macports accepts community contributions here: https://github.com/macports/macports-ports
