### ISSUE TITLE
Actions Exec requires global git user/email config

### ISSUE THREAD

**Issue by adam-moss** [sourcegraph/src-cli#256]
`exec` of `src actions` appears to require a globally configured `git config user.name` and `git config user.email` rather than using that locally defined in a repository (if one exists).

**Comment by eseliger** [comment]
Thank you for reporting this issue!
We actually just use `git` internally, and the value of author and email doesn't have any effect on the commits that are going to be created on your code host. So it doesn't matter what values are set, but it should definitely not fail if there is no global config and you found a bug here! We're going to fix that.

**Comment by mrnugget** [comment]
Hey @adam-moss, how did you come to the conclusion that it requires a global config? Because of the committer name/email that sourcegraph uses when creating pull requests?

**Comment by adam-moss** [comment]
I have my campaigns in version control. My global git config only has my user name, I set the email address depending on where I'm pushing the repo as a git config within the repo.

So internally I use my work email for example, and public I may us that or I may use the auto-generated GitHub/GitLab masked email.

The error message thrown was complaining about not have email set globally.

**Comment by adam-moss** [comment]
The committer name/email used on creation of merge requests is a different issue (not one I've raised other than with Dan in Slack), but I also need to understand how that is configured 👍

**Comment by mrnugget** [comment]
Thanks! Now I understand.

> The error message thrown was complaining about not have email set globally.

I didn't get that it's about an error message. I assumed it was about the wrong data showing up somewhere.

**Comment by adam-moss** [comment]
Well, it is wrong data also - when the commit lands on the code host it definitely doesn't have any of our configured details, it has yours 🙄

**Comment by mrnugget** [comment]
Yep, that's a separate issue that we'll address in the near future. We're currently reshaping the workflows around campaigns and once neat side effect of that is that it'll be really easy for users to configure things like that.
