### ISSUE TITLE
src campaigns: unknown subcommand "apply"

### ISSUE THREAD

**Issue by wimo7083** [sourcegraph/src-cli#259]
I upgraded to sourcegraph `Version: 3.18.0` yesterday. Today I am attempting the [hello world](https://docs.sourcegraph.com/user/campaigns/hello_world_campaign) tutorial for sourcegraph campaigns. 

This is the [docker image](https://hub.docker.com/layers/sourcegraph/server/3.18.0/images/sha256-12df070d0532161d3d7355327b212ca1ec20d17dad42ccaa30608e0df9027824?context=explore) I am using.

```bash
$ src campaigns apply
src campaigns: unknown subcommand "apply"
Run 'src campaigns help' for usage.

$ src version
Current version: 3.16.1
Recommended Version: 3.16.1
```

I have tried to install both ways recommended:
 - [version compatible with your sourcegraph instance](https://github.com/sourcegraph/src-cli#version-compatible-with-your-sourcegraph-instance-1)
- [latest version](https://github.com/sourcegraph/src-cli#latest-version-1)

What do you suggest?

**Comment by mrnugget** [comment]
Hey @wimo7083! Sorry about that! We're currently in the middle of switching to a new workflow for campaigns, which introduces the `campaigns apply` command. That's not supported in `src` yet (see progress here https://github.com/sourcegraph/src-cli/pull/260).

Our docs at docs.sourcegraph.com though show the docs for the `master` branch of Sourcegraph. At the top of the campaigns documentation you should see a little notice warning you about that and linking you to the docs for 3.18, which you can [find here](https://docs.sourcegraph.com/@3.18/user/campaigns).

Let me know if that helps!

**Comment by wimo7083** [comment]
Thank you for the reply, I'll try and follow that change as we are very interested in the use of campaigns.

**Comment by alexturek** [comment]
@mrnugget Would SourceGraph object to switching what branch of the docs is shown for `docs.sourcegraph.com`? It seems like these docs [have been broken for 20 days now](https://github.com/sourcegraph/sourcegraph/pull/11675)

It's not super clear that the docs are a WIP. That's also not my expectation when viewing the docs of any other product/service.

**Comment by mrnugget** [comment]
@alexturek Yes, absolutely! I'll bring it up.
