### ISSUE TITLE
lsif upload exposes a new command line flag `-upload-route` that is intended for internal use only

### ISSUE THREAD

**Issue by aidaeology** [sourcegraph/src-cli#269]
A new flag `-upload-route` was recently added to `src lsif upload` command and is included in the usage/help text displayed to user, however the only current use for it is internal and the value is hardcoded inline:

https://github.com/sourcegraph/sourcegraph/blob/3df0a1bb364e847647f45fecc90dc141ee2abd1d/enterprise/cmd/precise-code-intel-indexer-vm/internal/indexer/handler.go#L62

This is a usability issue, since users can't actually use this flag. We should only expose flags that are functional. Suggest to hide this flag or use another implementation method.

**Comment by macraig** [comment]
@efritz any idea about the status of this?

**Comment by efritz** [comment]
```
  -upload-route string
    	The path of the upload route. For internal use only. (default "/.api/lsif/upload")
```
