### ISSUE TITLE
src ext delete should take extension ID, not GraphQL ID (which is confusing)

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/src-cli#27]
For a correctly configured extension, `src ext publish` succeeds, but `src ext delete` does not.

The error returned is:

```
GraphQL errors:
[
  {
    "message": "invalid graphql.ID",
    "path": [
      "extensionRegistry",
      "deleteExtension"
    ]
  }
]
```

**Comment by slimsag** [comment]
It does actually work, I assume you are passing the _extension ID_ into `src ext delete` and that is causing the issue. You should be passing in the _GraphQL ID_ into `src ext delete`. Consult `src ext delete -h` for examples.

I agree this is confusing from a user POV though, and I remember raising this with @sqs during code review, but I don't remember the outcome of that conversation.

**Comment by ryan-blunden** [comment]
I naively expected `src ext delete` to work the same way as `src ext publish` (without arguments). I understand why it doesn't work that way now as deleting an extension is not dependent on having the extension code available.

@sqs: What do you think of the suggestion to attempt to lookup the GraphQL ID using the extension name from the `package.json` in the current directory (presuming its being run in the extension code directory) if no GraphQL id is supplied?

**Comment by slimsag** [comment]
I think just `src ext delete my-extension-id` is what users would expect. I find using the ID from package.json dangerous -- what if I run the command in the wrong directory by accident?

**Comment by slimsag** [comment]
Great, updated title to make that the action item here. This should be a trivial / straightforward change to make if anyone unexperienced with this codebase wants a good starter issue

**Comment by ryan-blunden** [comment]
I can take it on.

**Comment by felixfbecker** [comment]
Just met this too.

**Comment by eseliger** [comment]
Extensions have been deprected, so I am going to close this ticket as part of some backlog grooming. Please reopen if you think we should still care about it.
