### ISSUE TITLE
campaigns: make log and cache directories configurable

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/src-cli#316]
Right now, both the log and cache directories are hardcoded, but there's no real reason they should be. They should be configurable, ideally through a combination of environment variables and command line flags.

**Comment by mrnugget** [comment]
Can't you set the cache directory with the `-cache` flag?

**Comment by mrnugget** [comment]
Closing this because #318 allows setting the directory used for logs with `-tmp` and `-cache` already exists.
