### ISSUE TITLE
README references nonexistant `src login` subcommand

### ISSUE THREAD

**Issue by EvanKrall** [sourcegraph/src-cli#332]
The [readme](https://github.com/sourcegraph/src-cli#log-into-your-sourcegraph-instance) tells me to run `src login`, but that just gives me `src: unknown subcommand "login"`.

Looks like there's [an open issue](https://github.com/sourcegraph/src-cli/issues/28) for creating such a subcommand?

**Comment by mrnugget** [comment]
Hey! Which version of src-cli are you on? The newest version, `3.21.0`, has it: https://github.com/sourcegraph/src-cli/releases/tag/3.21.0

**Comment by EvanKrall** [comment]
Well, I thought I was on the latest version, because I followed the instructions on the README for [getting the latest version](https://github.com/sourcegraph/src-cli#latest-version-1), but the [download link](https://sourcegraph.com/.api/src-cli/src_linux_amd64) seems to be 3.20.0. I guess that's the real bug here.

**Comment by mrnugget** [comment]
Ah, you're right. That's a bug. I'll look into it, thank you.

**Comment by mrnugget** [comment]
Looks like we just forgot to bump the "latest" version on Sourcegraph.com. Sorry about that! https://github.com/sourcegraph/sourcegraph/pull/14324 should fix it.

**Comment by EvanKrall** [comment]
Great, thanks!
