### ISSUE TITLE
campaigns: worker display is misleading if fewer workers are required than the limit

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/src-cli#348]
If you have a small campaign, or a campaign with almost all its changesets already cached, you can end up with unneeded workers being seemingly stalled in the UI:

![image](https://user-images.githubusercontent.com/229984/95904008-c4c6c000-0d4b-11eb-9d63-7bd38ef552d6.png)

Those "Starting worker..." lines should probably either not exist, or be greyed out with something like "Nothing to do!" as the label.

**Comment by mrnugget** [comment]
Interesting! I thought that would be fixed by the change to `initProgressBar` in https://github.com/sourcegraph/src-cli/pull/341/files
