### ISSUE TITLE
Make src-config file hidden and chmod it

### ISSUE THREAD

**Issue by P3GLEG** [sourcegraph/src-cli#37]
You should ensure that the file is considered "hidden" as a good practice. `$HOME/.src-config.json` as well as perform a `chmod 600` on it. Not the craziest thing in the world but it's weird having it found on my desktop.

**Comment by slimsag** [comment]
Thanks for filing this, I definitely agree! Not sure how we missed this.

**Comment by P3GLEG** [comment]
Probably best to put it in ~/.sourcegraph/config. No worries.

**Comment by sluongng** [comment]
actually please follow the convention by many other tools and put the config in `$HOME/.config/sourcegraph/config.json`

**Comment by joshuabezaleel** [comment]
Hi everyone, I want to clarify something if I may. cc: @slimsag 

So far the only part of the code that I saw mentioned `src-config.json` is in the `main.go`'s [`readConfig`](https://github.com/sourcegraph/src-cli/blob/master/cmd/src/main.go#L84) and is only used when the user supplied their own endpoint and access token and not using the environment variable which then will be overrided by the program's manual assignment if there isn't any argument to the `-config` flag, right? 
Is there any part of the code that saves and output any config to the `src-config.json` that I miss? 

Thank you very much in advance :slightly_smiling_face:

**Comment by slimsag** [comment]
@joshuabezaleel that is correct, and no, nothing writes to the file.
