### ISSUE TITLE
campaigns validate hangs

### ISSUE THREAD

**Issue by evanweible-wf** [sourcegraph/src-cli#383]
src version: 3.22.0

I've tried running `src campaigns validate` on a couple different campaign specs (including the hello world example from the docs) and it just hangs, no output whatsoever. Waited a couple of minutes before giving up.

**Comment by mrnugget** [comment]
@evanweible-wf did you use the `-f` flag with `src campaigns validate`? If you don't provide a `-f` flag, `src campaigns validate` will wait for input on standard input.

**Comment by mrnugget** [comment]
I opened https://github.com/sourcegraph/src-cli/pull/384 to help with the problem of `src campaign [validate|preview|apply]` silently waiting for input if the user forgot a `-f` flag but provided an additional arg (a filename)

**Comment by evanweible-wf** [comment]
Whoops, yes I did forget the `-f` :) Sorry about that! I'll go ahead and close this, and thanks for filing the other issue!
