### ISSUE TITLE
Running Campaign as sudo

### ISSUE THREAD

**Issue by janstadt** [sourcegraph/src-cli#408]
I was having an issue with the cli when running a campaign locally on a single instance docker install. I am not an admin on the box its running on (or the cli) so i had to elevate using `sudo` when running src-cli. I kept getting an error about not being able to resolve the namespace of my user even though i had the proper env variable set. 

I fixed this by preserving environment variables (`-E` or `--preserve-env`) with the following call:

`sudo -E src campaign preview -f rename-depricated-fqdns.yaml` 

I dont think this a functionality issue with the cli but it would be nice to have some documentation mentioning this. If i missed it in the docs, my bad, but just a heads up.

**Comment by mrnugget** [comment]
@janstadt Thanks for reporting this!

@LawnGnome I just came across this ticket again. It seems like you've extended the docs to mention this. Can you open a PR for that?
