### ISSUE TITLE
`src extensions list` fails with a GraphQL error

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/src-cli#42]
When I try to list Sourcegraph extensions with `src` I get the following output:

```
$ SRC_ACCESS_TOKEN=<my_token> SRC_ENDPOINT=http://localhost:7080 src extensions list
GraphQL errors:
[
  {
    "locations": [
      {
        "column": 9,
        "line": 29
      }
    ],
    "message": "Cannot query field \"title\" on type \"ExtensionManifest\"."
  }
]

```

I'm using Sourcegraph 3.4.0-rc.5 running as a Docker container

**Comment by slimsag** [comment]
Try updating your 'src' tool, I tried this just last night with latest and
it worked

**Comment by mrnugget** [comment]
This was the latest, downloaded as instructed by the macOS instructions in
the README

**Comment by slimsag** [comment]
Oh my bad I misread this as 'src REPOS list', you are right this is broken

**Comment by mrnugget** [comment]
This seems to have been fixed, since I cannot reproduce it.
