### ISSUE TITLE
Can't log in to SourceGraph with self-signed certificate

### ISSUE THREAD

**Issue by JohnAZoidberg** [sourcegraph/src-cli#463]
I set Sourcegraph up with a self-signed certificate, as described here: https://docs.sourcegraph.com/admin/ssl_https_self_signed_cert_nginx

Now I try to log in with the `src` command but it won't accept it and I can't figure out a way to ignore it. Adding `insecure` to `~/.curlrc` doesn't work.

```
daniel@daniel-virtual-machine:~$ src login https://15.1.1.1:7443
❌ Problem: Error communicating with https://15.1.1.1:7443: Post "https://15.1.1.1:7443/.api/graphql": x509: certificate signed by unknown authority

🛠  To fix: Create an access token at https://15.1.1.1:7443/user/settings/tokens, then set the following environment variables:

   SRC_ENDPOINT=https://15.1.1.1:7443
   SRC_ACCESS_TOKEN=(the access token you just created)

   To verify that it's working, run this command again.

   (If you need to supply custom HTTP request headers, see information about SRC_HEADER_* env vars at https://github.com/sourcegraph/src-cli/blob/main/AUTH_PROXY.md.)
```

Should be easily doable like #239 but I don't feel like compiling Go programs at the moment.

**Comment by JohnAZoidberg** [comment]
Of course I can add the root CA as a system-wide trusted CA but I'd prefer to rather have the `src` command ignore the failure or accept a path to my CA.

**Comment by mrnugget** [comment]
Thanks for reporting @JohnAZoidberg! We'll take a look.

**Comment by jallenwork** [comment]
+1 on this, my teammates using macOS for development can't login to our self signed instance with the `src` utility. We have our certs available in the macOS keychain, but it seems like the `src` tool isn't respecting that?

**Comment by JohnAZoidberg** [comment]
> Of course I can add the root CA as a system-wide trusted CA but I'd prefer to rather have the `src` command ignore the failure or accept a path to my CA.

On my development machine I need to add the cert to my browser to visit the website and make the plugin work. Or I can add it to the system certs.

But I'm opening this issue because I wanted to upload my generated LSIF to sourcegraph from the build server, which doesn't need the cert for any other purpose than this single action.
