### ISSUE TITLE
homebrew mac 3.24.6 point at wrong name for src file

### ISSUE THREAD

**Issue by jensim** [sourcegraph/src-cli#469]
So, it seems that the latest brew release does not install the correct name for mac os
Formula point at `src-cli`
but the packge contains only `src`

This is the breaking commit
https://github.com/sourcegraph/homebrew-src-cli/commit/282b5131038d9b071c44f4c852d0863eaae0252b

```ruby
#/usr/local/Homebrew/Library/Taps/sourcegraph/homebrew-src-cli/Formula/src-cli.rb

# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCli < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "3.24.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sourcegraph/src-cli/releases/download/3.24.6/src-cli_3.24.6_darwin_amd64.tar.gz"
    sha256 "3f8e00e09fa3e7d5c2174f3077fdfe081faaef7e6b982d8f9658fab891ba42dc"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sourcegraph/src-cli/releases/download/3.24.6/src-cli_3.24.6_linux_amd64.tar.gz"
    sha256 "1daa7c5e3c590e69a777d5fb415eac07dbb0d5c9ccc0b67799c5958442087ec9"
  end

  def install
    bin.install "src-cli"
  end
end
```

```shell
➜  tar tvf /Users/$(whoami)/Library/Caches/Homebrew/downloads/bbfb83d1675e5f363cf7c9ec7177ae333d1903d11acefe9295627869813d1293--src-cli_3.24.5_darwin_amd64.tar.gz
-rw-r--r--  0 runner docker  18439 Feb 13 01:43 CHANGELOG.md
-rw-r--r--  0 runner docker  11357 Feb 13 01:43 LICENSE
-rw-r--r--  0 runner docker   5045 Feb 13 01:43 README.markdown
-rwxr-xr-x  0 runner docker 15527184 Feb 13 01:44 src
```

**Comment by mrnugget** [comment]
Thanks for reporting! The `homebrew-src-cli` repo is updated by `goreleaser` which runs on a release here: https://github.com/sourcegraph/src-cli/blob/3ff17a2052f13b2f795506250581bfba59575814/.goreleaser.yml#L29-L39

Something in the goreleaser config must have changed. Maybe it was the removal of the `docker.binaries` step here? https://github.com/sourcegraph/src-cli/commit/2afb9e1405850ab11a4b1186b26253ac5a63df8b

**Comment by mrnugget** [comment]
I fixed this on `main` and cut a new release. 3.24.7 has `src` as the binary name: https://github.com/sourcegraph/homebrew-src-cli/commit/9127850dfa70462fbef5df2a057c6defdf0515fc Thanks for reporting this!

**Comment by jensim** [comment]
Nice! Thanks for addressing this so fast!
