### ISSUE TITLE
Document access token configuration in the README

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/src-cli#5]
Since everyone needs to do this, I think it should be documented in the README.

**Comment by felixfbecker** [comment]
Is the CLI expected to not work without an access token? Why does it require one if I can use sourcegraph.com without signing up?

**Comment by slimsag** [comment]
I missed this due to being on vacation at the time it was discussed. I agree it should work without an access token, I wrote it with the assumption it needed one because that was the primary use case at the time. I'm relaxing this constraint now.
