### ISSUE TITLE
SRC_ENDPOINT not respected?

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/src-cli#51]
I set `SRC_ENDPOINT` to my local instance. Running `src campaigns list` did not return anything, despite campaigns existing in the UI.
Then I also set `SRC_ACCESS_TOKEN`, and got
```
error: 401 Unauthorized

Invalid access token.
```
The fact that I just created this token yet it is invalid tells me that `SRC_ENDPOINT` is not respected.

Passing `-endpoint` explicitly works.

**Comment by mrnugget** [comment]
I cannot reproduce this. Is this still an issue?

```
$ SRC_ACCESS_TOKEN=<TOKEN> src campaigns list
error: 401 Unauthorized

Invalid access token.
$ SRC_ACCESS_TOKEN=<TOKEN> SRC_ENDPOINT=http://localhost:3080 src campaigns list
```

**Comment by felixfbecker** [comment]
Guess it was fixed 🤷‍♂

**Comment by slimsag** [comment]
I suspect that you hadn't updated binary from before this environment
variable was added
