### ISSUE TITLE
Batch changes preview link has an "l" at the beginning

### ISSUE THREAD

**Issue by evanweible-wf** [sourcegraph/src-cli#513]
src version: 3.26.3

When previewing a batch spec, the preview URL it outputs has an `l` at the beginning, making it an invalid URL:

```
2021-04-15T15:42:13.864845940Z ✅ To preview or apply the batch spec, go to:
2021-04-15T15:42:13.864856235Z    lhttps://sourcegraph.[redacted...]
```

**Comment by mrnugget** [comment]
Hey! Well, that's weird. What's the value in your `SRC_ENDPOINT`? 

Because we only prepend that to the path:

https://github.com/sourcegraph/src-cli/blob/a6beb127c00b259e20b93c9fff3e37d7da3b17b2/cmd/src/batch_preview.go#L64-L66

**Comment by evanweible-wf** [comment]
Whoops! Looks like this must be an issue with the log viewer on our CI runner, this works as expected locally and when I download the logs I can see where the `l` is coming from:

```
[?25[34m[4mlhttps://sourcegraph...
```

Sorry about the false report!
