### ISSUE TITLE
Windows Powershell error: `exec: "less": executable file not found in %PATH%`

### ISSUE THREAD

**Issue by Eibwen** [sourcegraph/src-cli#554]
Following https://docs.sourcegraph.com/cli/explanations/windows

along with https://docs.sourcegraph.com/cli/quickstart#run-a-code-search

For every search I try to do, I get the error

Here is a log of my console:

```
PS> src login
✔️  Authenticated as {my user} on https://{server address}
PS> src version
Current version: 3.28.3
Recommended version: 3.28.3 or later
PS> src search 'name'
exec: "less": executable file not found in %PATH%
PS> src search 'super specific thing'
exec: "less": executable file not found in %PATH%
PS> src search 'lang:c#'
exec: "less": executable file not found in %PATH%
```

It appears that tool doesn't exist on my system, and I'm not seeing any guidance about how to get that installed in your docs. Including that in the docs might be worthwhile

## Attempted solution

`Find-Package pscx | Install-Package -AllowClobber` after modifying the command from https://stackoverflow.com/a/1080103/356218

This did not seem to work well.  There was no error, but the display doesn't seem to show results as I was expecting, it is only a black screen until I type `q` or otherwise exit `less`

**Comment by mrnugget** [comment]
Hey @Eibwen! Thanks for the ticket. We'll look into it.

**Comment by LinqLover** [comment]
Same issue here, available for further info if you need anyone

**Comment by mrnugget** [comment]
Can you confirm that it works if you disable paging the output to `less` by using

```
src search -less=false <your search query>
```

**Comment by LinqLover** [comment]
> Can you confirm that it works if you disable paging the output to `less` by using
> 
> ```
> src search -less=false <your search query>
> ```

Confirmed! Probably these binaries should always be installed with src-cli on Windows: http://www.greenwoodsoftware.com/less/download.html

**Comment by mrnugget** [comment]
Thanks! I just opened #644 that checks for the existence of `less` before trying to use it.

**Comment by LinqLover** [comment]
Hm, but this reduces the functionality of this CLI. Wouldn't it be possible to always ship `less` via the installer (provided that no license terms are violated)?

**Comment by mrnugget** [comment]
`less` is one of the standard pagers installed on macOS and Linux, which are the primary OSes we support here. Adding support for installing dependencies on Windows is, I think, out of the scope of our Windows support :)

**Comment by LinqLover** [comment]
Alright, then I will probably use `src-cli` in my Windows Subsystem for Linux instead. Thank you for your help. :)

**Comment by mrnugget** [comment]
Yeah, or you install `less` from the link you posted. That would make `less` available and `src-cli` would use it.
