### ISSUE TITLE
batches: investigate switching to POSIX paths on Windows

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/src-cli#563]
We [have a report](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1625167825240600) that bind mounts can fail in some Windows environments because we're using DOS style paths instead of POSIX. This is an easy change on a technical level, but we need to ensure we test the various Docker deployment options to verify that this is safe, and that's not easy.

**Comment by malomarrec** [comment]
Closing, as windows support is not on our roadmap for the next 2 quarters.
If you come across this, and windows support is important to you, feel free to drop a comment in this thread to help us prioritise this up!
