### ISSUE TITLE
Failed to upload an index to a Sourcegraph local instance. 

### ISSUE THREAD

**Issue by ManuelG28** [sourcegraph/src-cli#656]
I've never had issues uploading an index to sourcegraph.com but on this occasion, I'm trying to upload to my local instance running in docker. 
💡 Inferred arguments
   repo: github.com/ManuelG28/tutorial
   commit: 390f69cdde5a02763764f5d71a0844fac855211a
   root:
   file: ./dump.lsif
   indexer: sigasi

✅ Index compressed
💡 Indexed compressed (0.19MB -> 0.02MB).
❌ Failed to upload index file
Post "05b6dfa4caf798d31172128d124656e39a140598/.api/lsif/upload?commit=390f69cdde5a02763764f5d71a0844fac855211a&indexerName=sigasi&repository=github.com%2FManuelG28%2Ftutorial": unsupported protocol scheme ""

The result using the `-trace=3` flag
💡 Inferred arguments
   repo: github.com/ManuelG28/tutorial
   commit: 390f69cdde5a02763764f5d71a0844fac855211a
   root:
   file: ./dump.lsif
   indexer: sigasi

> POST 05b6dfa4caf798d31172128d124656e39a140598/.api/lsif/upload?commit=390f69cdde5a02763764f5d71a0844fac855211a&indexerName=sigasi&repository=github.com%2FManuelG28%2Ftutorial
> Request Headers:
>     Authorization: [token my-sourcegraph-token]
>     Content-Type: [application/x-ndjson+lsif]

Post "05b6dfa4caf798d31172128d124656e39a140598/.api/lsif/upload?commit=390f69cdde5a02763764f5d71a0844fac855211a&indexerName=sigasi&repository=github.com%2FManuelG28%2Ftutorial": unsupported protocol scheme ""

**Comment by mrnugget** [comment]
cc @sourcegraph/code-intel

**Comment by Strum355** [comment]
Hi @ManuelG28, it looks like you dont have `SRC_ENDPOINT` (and possibly the `SRC_ACCESS_TOKEN`) environment variables set. You can read more about them [here](https://docs.sourcegraph.com/cli/explanations/env#src-endpoint). The [src-cli quickstart](https://docs.sourcegraph.com/cli/quickstart#connect-to-sourcegraph) might also be helpful here. Let us know if you have any issues with the docs or getting the instructions to work for your instance :slightly_smiling_face:

**Comment by ManuelG28** [comment]
@Strum355 I followed the steps before uploading it and I tested running `src login` again. 

![image](https://user-images.githubusercontent.com/36460775/141486091-169813c9-c00c-4573-9276-aea04e6e53cb.png)

Also, I followed this https://beyang.org/fastest-sourcegraph.html to change my external URL.

Am I forgetting something?

**Comment by Strum355** [comment]
Have you set the SRC_ENDPOINT env var to https://af36-82-134-64-38.ngrok.io? Looking at the error message it looks like you may have set the access token as the endpoint by mistake. Could you double check the env vars are correct? 🙂

**Comment by ManuelG28** [comment]
Sorry for continue having the problem, I tried to delete my access point and set up the env vars again. 

![image](https://user-images.githubusercontent.com/36460775/141496659-66ee2ca4-3cc2-4c36-8ac9-2900cbb7a9d0.png)

**Comment by efritz** [comment]
@ManuelG28 Looks like you're supplying `-endpoint=<access token>`. Can you try removing that flag from your `src lsif upload` invocation?

**Comment by ManuelG28** [comment]
@efritz Solved, thank you and sorry for my mistake.

**Comment by efritz** [comment]
@ManuelG28 No worries, `-endpoint` has been a thorn in my side as well 😉.
