### ISSUE TITLE
Replace `_` with `-` in custom headers

### ISSUE THREAD

**Issue by nihaals** [sourcegraph/src-cli#749]
Headers usually use `-` as opposed to `_`, and some auth proxies may only support `-`. As setting environment variables with dashes is [more complex than underscores](https://unix.stackexchange.com/questions/23659/can-shell-variable-name-include-a-hyphen-or-dash), maybe it makes sense to replace them. This would technically be a breaking change if an auth proxy only supported underscores.

An example of a case where the proxy does not support underscores but does support dashes is Cloudflare Access (with service tokens, [more info](https://community.cloudflare.com/t/access-service-token-headers-underscore-inconsistency/385833)).

**Comment by mrnugget** [comment]
Hey @nihaals! What custom headers are you referring to? I don't see where [we set headers with an underscore in them](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/src-cli%24+Header.Set&patternType=literal) and if you pass in custom headers to be sent along [you decide what they look like](https://sourcegraph.com/github.com/sourcegraph/src-cli/-/blob/cmd/src/headers_test.go?L15-20).

**Comment by nihaals** [comment]
> Maybe we could introduce something like `SRC_HEADERS` which contains a newline-separated list of headers? `SRC_HEADERS="My-cool-header: one\nMy-other-cool-header: two"`.

I think this would be an interesting approach, although it would need to be tested in bash, zsh and fish to make sure it's ergonomic and not just as awkward as using `env`.
