### ISSUE TITLE
Possible release version error

### ISSUE THREAD

**Issue by lmartinez-mirror** [sourcegraph/src-cli#776]
The latest release reads "4.30.9" where I think someone meant "3.40.9", unless there really are significant breaking changes to warrant a major version upgrade.

**Comment by mrnugget** [comment]
Yes, you're right! Sorry about that. We'll fix this.

**Comment by eseliger** [comment]
Fixed! Thanks for reporting :)

**Comment by courier-new** [comment]
How embarrassing for whoever mixed up the numbers like that!

(Not sure where my brain was at yesterday, but thanks for catching this, @lmartinez-mirror! 😂🙇‍♀️)
