### ISSUE TITLE
Tracking: TODOs `src users prune`

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/src-cli#833]
This is a tracking issue for the forthcoming `src users prune` command: https://github.com/sourcegraph/src-cli/pull/826

## TODOS
- Add an email functionality to email removed users, open vim editor like in git commit
- Write json file containing users to be deleted, last active usage, site-admin status, and emails. _This is so that admins can potentially do their own programmatic analysis around who *would* be removed before removing users_

**Comment by DaedalusG** [comment]
- Processing work for this command should be moved to the Sourcegraph instance to prevent lots of data transfer over network. In instances with many users the current graphQL request takes way too long to process. For more details see [comment](https://github.com/sourcegraph/src-cli/pull/826#discussion_r960392615) in initial PR

**Comment by DaedalusG** [comment]
User feedback: 
- provide -dry-run option which outputs the list of users to be deleted (_this may be addressed by the json output bullet_)
- provide an input method for users to specify a list of users explicitly not to be deleted

**Comment by hopkinscl** [comment]
User feedback (from account #[8247](https://github.com/sourcegraph/accounts/issues/8247))

- Allow users to pass a value <60 via the `-days` flag (customer in question does clean-up every 2 weeks)

**Comment by DaedalusG** [comment]
Hey @hopkinscl the 60 days constraint was a condition to release this provided by @ryphil -- originally rhe command allowed any value for days, but the idea was to prevent admins from using this too frequently. Happy to change that if its not a major concern.

**Comment by DaedalusG** [comment]
Tracking issue https://github.com/sourcegraph/src-cli/issues/848

**Comment by DaedalusG** [comment]
Opened an issue to inform on gateway timeout problem, and track improvements planned in this area: https://github.com/sourcegraph/src-cli/issues/848

**Comment by DaedalusG** [comment]
- Move away from use of `usageStatistics` graphQL enpoint to use of the new `aggregated_user_statistics` table:
https://github.com/sourcegraph/sourcegraph/pull/40301

Currently users who have never been active or have not been active for 93 days will have a null value for `lastActiveUsage` in the graphQL `userStatistics` endpoint this causes difficulties and confusion in the cleanup script 

`event_logs` only stores a record for 93 days and `lastActiveTime` is determined from the last `event_log` entry associated to a user -- `lastActiveAt` is recorded in the `aggregated_user_statistics` table from `lastActiveTime` but its then persisted there.

_Not its unclear wether or not this will help at all with the timing out network request noted in https://github.com/sourcegraph/src-cli/issues/848_

**Comment by rakeshjosh2003** [comment]
One of the customer has requested if we can allow less than 60 days in -days flag. 

[Account](https://github.com/sourcegraph/accounts/issues/562)
[related thread](https://sourcegraph.slack.com/archives/C018U1ZRFQC/p1683685368581979)
