### ISSUE TITLE
src login not working

### ISSUE THREAD

**Issue by ghirsch-reddit** [sourcegraph/src-cli#840]
I installed src-cli via homebrew, generated an API token, and set the `SRC_ENDPOINT` and `SRC_ACCESS_TOKEN` variables. When I then try to run `src login SOURCEGRAPH_URL` with the URL of our private Sourcegraph instance, I get a response of

```
❌ Problem: Error communicating with <SOURCEGRAPH_URL>: invalid character '<' looking for beginning of value
```

When I try to recreate the request that happens [here](https://github.com/sourcegraph/src-cli/blob/main/cmd/src/login.go#L102-L106), I get a 303 HTML response, which explains the response from `src login` but seems unexpected.

Is there some further configuration that users need to do beyond the things mentioned at the top? Or is this likely a bug with Sourcegraph? If the former, it also seems worth updating the error messages to point others who run into the same thing in the right direction.

**Comment by mrnugget** [comment]
Just to be sure, you _did_ replace `<SOURCEGRAPH_URL>` in the commands and env vars with the actual values, right?

**Comment by ghirsch-reddit** [comment]
Correct, I used the actual values for setting env vars and running commands.

Also perhaps of note is that the 303 redirects me to an OAuth flow.

**Comment by ghirsch-reddit** [comment]
Okay actually I found the issue, turns out I needed to connect to our VPN.

Let me know if I should just close this ticket, or if I should leave it open since others with private instances may have similar problems, and a better error message could be valuable

**Comment by LawnGnome** [comment]
We discussed this issue at our team sync this morning and are going to close it for now, since you have src-cli working, but we may revisit the exact error message at a later date. Thanks for opening the issue!
