### ISSUE TITLE
Is there any plans for TUI

### ISSUE THREAD

**Issue by z0xyz** [sourcegraph/src-cli#991]
The current CLI version is great but it's quite limiting in terms of navigation within a certain project. Like When the search results does match my query, but if I wanted to inspect a certain project in real time, then it's not possible.
Is there any plans for a TUI version in the future?

**Comment by mrnugget** [comment]
Hey @z0xyz, no, currently there are no plans for a TUI. I think the closest you'll find to client-side utility that allows one to explore projects is https://docs.sourcegraph.com/app

**Comment by z0xyz** [comment]
hello. The client got taken down. Is there an alternate way to have it back?

**Comment by z0xyz** [comment]
hello @mrnugget. The client got taken down. Is there an alternate way to have it back?

**Comment by mrnugget** [comment]
I assume with client you mean App? I'm not sure, to be honest, but I don't think there's a way to get it back right now. cc @taylorsperry

**Comment by z0xyz** [comment]
> I assume with client you mean App?
Yup. The one installed locally to index local self-hosted repos.

**Comment by z0xyz** [comment]
@mrnugget I've tried to install the docker `self-hosted` [container](https://about.sourcegraph.com/get-started/self-hosted), but the web client was vastly different. That's the closest thing I can think of that similar to the [search interface](https://sourcegraph.com/search)

**Comment by taylorsperry** [comment]
Yes, the Cody App was [deprecated](https://docs.sourcegraph.com/cody/faq#what-happened-to-the-cody-app) as part of our December launch. You can now index local repos through the Cody [extension](https://marketplace.visualstudio.com/items?itemName=sourcegraph.cody-ai) for VS Code, and we're working to bring the same capability to JetBrains soon!

**Comment by z0xyz** [comment]
@taylorsperry
> the Cody App was deprecated

 Is there a way to least get the old deprecated appimage? I'm not using VSCode, and JetBrains interface is limiting enough for me, that I use the [web interface](https://sourcegraph.com/search) for searching remote repos.
